title: "La Vida Luca"
description: "Réseau de fermes pilotes bio, innovantes et sociales"
email: "vidaluca77@gmail.com"
phone: ""
address: |
  Souleuvre-en-Bocage
  14350 Calvados
  France

social:
  facebook: "https://www.facebook.com/share/16rgTShcag/?mibextid=wwXIfr"
  instagram: ""
  linkedin: "https://www.linkedin.com/in/lucas-horville-50a500380/"